import {
  pgTable, text, timestamp, primaryKey, integer,
} from 'drizzle-orm/pg-core';

/**
 * Auth.js session store — MIGRATION-PLAN §10.
 *
 * The shape here is dictated by @auth/drizzle-adapter, not by us: the adapter
 * queries these column names directly. Written out explicitly rather than
 * generated by the adapter's `defineTables` helper because it lands in a
 * migration against a live database, and a schema nobody can read is a schema
 * nobody can review.
 *
 * Scope is ~9 internal editors signing in with an emailed link. There are no
 * public accounts and no password column — there are no passwords.
 */

export const users = pgTable('users', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text('name'),
  email: text('email').notNull(),
  emailVerified: timestamp('email_verified', { withTimezone: true }),
  image: text('image'),
});

/**
 * Required by the adapter interface and expected to stay empty: nothing here
 * uses an OAuth provider today. It exists so switching to Google Workspace SSO
 * later is a config change rather than another migration.
 */
export const accounts = pgTable('accounts', {
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  type: text('type').notNull(),
  provider: text('provider').notNull(),
  providerAccountId: text('provider_account_id').notNull(),
  refresh_token: text('refresh_token'),
  access_token: text('access_token'),
  expires_at: integer('expires_at'),
  token_type: text('token_type'),
  scope: text('scope'),
  id_token: text('id_token'),
  session_state: text('session_state'),
}, (t) => [
  primaryKey({ columns: [t.provider, t.providerAccountId] }),
]);

export const sessions = pgTable('sessions', {
  sessionToken: text('session_token').primaryKey(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  expires: timestamp('expires', { withTimezone: true }).notNull(),
});

/** The emailed sign-in link, single-use: the adapter deletes the row on redeem. */
export const verificationTokens = pgTable('verification_tokens', {
  identifier: text('identifier').notNull(),
  token: text('token').notNull(),
  expires: timestamp('expires', { withTimezone: true }).notNull(),
}, (t) => [
  primaryKey({ columns: [t.identifier, t.token] }),
]);
