import type { Metadata } from 'next';
import { pageOg } from '@/lib/site';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The legally binding agreement between you and Rem Assistance Inc. governing your access to and use of our website, app, and services.',
  alternates: { canonical: '/terms-of-service' },
  openGraph: pageOg('/terms-of-service'),
};

export default function Page() {
  return (
    <main>
  
  
    
  <section style={{ background: "oklch(0.64 0.14 257)", backgroundImage: "radial-gradient(ellipse 900px 520px at 80% 10%, rgba(190,220,255,0.28), transparent 68%)", position: "relative", overflow: "hidden" }}>
      <div style={{ maxWidth: "1200px", margin: "0 auto", padding: "72px 24px 76px", position: "relative" }}>
        <p style={{ margin: "0 0 14px", fontSize: "12px", fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(255,255,255,0.85)", animation: "fadeUp 600ms cubic-bezier(0.2,0.8,0.2,1) both" }}>Legal</p>
        <h1 style={{ margin: "0 0 18px", fontFamily: "var(--font-display)", fontSize: "clamp(32px, 5.6vw, 52px)", fontWeight: 700, lineHeight: 1.08, letterSpacing: "-0.02em", color: "#fff", maxWidth: "18ch", textWrap: "pretty", animation: "fadeUp 600ms cubic-bezier(0.2,0.8,0.2,1) 80ms both" }}>Terms of Use</h1>
        <p style={{ margin: "0 0 28px", fontSize: "18px", lineHeight: 1.6, color: "rgba(255,255,255,0.92)", maxWidth: "60ch", animation: "fadeUp 600ms cubic-bezier(0.2,0.8,0.2,1) 160ms both" }}>The legally binding agreement between you and Rem Assistance Inc. that governs your access to and use of our website, app, and services.</p>
        <div style={{ display: "flex", alignItems: "center", gap: "20px", flexWrap: "wrap", animation: "fadeUp 600ms cubic-bezier(0.2,0.8,0.2,1) 240ms both" }}>
          <span style={{ display: "inline-flex", alignItems: "center", gap: "9px", background: "rgba(255,255,255,0.16)", border: "1px solid rgba(255,255,255,0.32)", borderRadius: "9999px", padding: "9px 18px", fontFamily: "var(--font-mono)", fontSize: "13px", color: "#fff" }}>Last updated 11 August 2026</span>
          <span style={{ width: "1px", height: "18px", background: "rgba(255,255,255,0.4)" }}></span>
          <span style={{ fontSize: "14.5px", color: "rgba(255,255,255,0.85)" }}>Effective immediately upon posting</span>
        </div>
      </div>
    </section>
  
  
    
  <section style={{ background: "var(--bg-marketing-paper)" }}>
      <div className={styles['legal-layout']}>
  
        <nav aria-label='Contents' style={{ position: "sticky", top: "104px", display: "flex", flexDirection: "column", gap: "2px", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "10px", boxShadow: "var(--shadow-sm)", padding: "22px 18px", maxHeight: "calc(100vh - 130px)", overflowY: "auto" }}>
          <div style={{ fontSize: "11.5px", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--ink-500)", padding: "0 8px 12px" }}>Contents</div>
          <a href='#agreement' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-1']}>Agreement to our legal terms</a>
          <a href='#services' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-2']}>1. Our services</a>
          <a href='#ip' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-3']}>2. Intellectual property rights</a>
          <a href='#representations' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-4']}>3. User representations</a>
          <a href='#registration' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-5']}>4. User registration</a>
          <a href='#payment' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-6']}>5. Purchases and payment</a>
          <a href='#refunds' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-7']}>6. Refund policy</a>
          <a href='#prohibited' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-8']}>7. Prohibited activities</a>
          <a href='#ugc' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-9']}>8. User generated contributions</a>
          <a href='#license' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-10']}>9. Contribution license</a>
          <a href='#reviews' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-11']}>10. Guidelines for reviews</a>
          <a href='#app' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-12']}>11. Mobile application license</a>
          <a href='#thirdparty' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-13']}>12. Third-party websites and content</a>
          <a href='#management' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-14']}>13. Services management</a>
          <a href='#privacy' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-15']}>14. Privacy policy</a>
          <a href='#termination' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-16']}>15. Term and termination</a>
          <a href='#modifications' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-17']}>16. Modifications and interruptions</a>
          <a href='#law' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-18']}>17. Governing law</a>
          <a href='#disputes' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-19']}>18. Dispute resolution</a>
          <a href='#corrections' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-20']}>19. Corrections</a>
          <a href='#disclaimer' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-21']}>20. Disclaimer</a>
          <a href='#liability' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-22']}>21. Limitations of liability</a>
          <a href='#indemnification' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-23']}>22. Indemnification</a>
          <a href='#userdata' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-24']}>23. User data</a>
          <a href='#electronic' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-25']}>24. Electronic communications</a>
          <a href='#california' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-26']}>25. California users and residents</a>
          <a href='#misc' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-27']}>26. Miscellaneous</a>
          <a href='#contact' style={{ fontSize: "14px", lineHeight: 1.45, color: "var(--ink-700)", textDecoration: "none", padding: "8px", borderRadius: "6px", transition: "all 150ms cubic-bezier(0.2,0.8,0.2,1)" }} className={styles['hv-28']}>27. Contact us</a>
        </nav>
  
        <div style={{ display: "flex", flexDirection: "column", gap: "44px", minWidth: 0 }}>
  
          <div id='agreement' style={{ background: "#fff", border: "1px solid var(--border-default)", borderRadius: "10px", boxShadow: "var(--shadow-sm)", padding: "34px 38px" }}>
            <h2 style={{ margin: "0 0 14px", fontFamily: "var(--font-display)", fontSize: "24px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>Agreement to our legal terms</h2>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)" }}>We are <strong style={{ color: "var(--brand-navy)" }}>Rem Assistance Inc.</strong>, doing business as Rem Assistance, Rem Connect, SAR Consulting, and SGA Software Solutions ("Company," "we," "us," "our"), a company registered in Texas, United States at 3733 Westheimer Rd, Ste #1-2058, Houston, TX 77027. We operate the website <a href='https://www.remassistance.com' target='_blank' rel='noopener'>remassistance.com</a> (the "Site"), our mobile application (the "App"), and any related products and services that link to these legal terms (collectively, the "Services"). We provide virtual assistance services to clients all around the world, catered and customized to each client's needs.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)" }}>You can contact us by phone at <a href='tel:+18322302194' style={{ fontWeight: 600 }}>(832) 230-2194</a>, by email at <a href='mailto:support@remassistance.com'>support@remassistance.com</a>, or by mail to 3733 Westheimer Rd, Ste #1-2058, Houston, TX 77027, United States.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)" }}>These legal terms are a legally binding agreement between you — personally or on behalf of an entity ("you") — and Rem Assistance Inc. concerning your access to and use of the Services. By accessing the Services you confirm that you have read, understood, and agreed to be bound by all of these terms. <strong style={{ color: "var(--brand-navy)" }}>If you do not agree with all of these legal terms, you are expressly prohibited from using the Services and must discontinue use immediately.</strong></p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)" }}>We will give you prior notice of any scheduled changes to the Services you are using. Modified terms become effective upon posting or upon notification via <a href='mailto:updates@remassistance.com'>updates@remassistance.com</a>. Continuing to use the Services after the effective date of any changes means you agree to be bound by the modified terms.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)" }}>The Services are intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to use or register for the Services. We recommend you print a copy of these terms for your records.</p>
          </div>
  
          <div id='services'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>1. Our services</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: use the Services only where it is legal to do so, and not for regulated-industry data.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction where such distribution or use would be contrary to law or regulation, or would subject us to a registration requirement there. People who access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws apply.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>The Services are not tailored to comply with industry-specific regulations such as HIPAA or FISMA — if your interactions would be subject to such laws, you may not use the Services. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</p>
          </div>
  
          <div id='ip'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>2. Intellectual property rights</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: everything in the Services is ours; you get a limited license to use it, and anything you send us becomes ours.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Our intellectual property</h3>
            <p style={{ margin: "0 0 22px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We own or license all intellectual property rights in our Services — source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics (the "Content"), plus the trademarks, service marks, and logos (the "Marks"). Content and Marks are protected by copyright and trademark laws and treaties in the United States and around the world, and are provided "AS IS" for your personal, non-commercial use or internal business purpose only.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Your use of our Services</h3>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Subject to your compliance with these terms — including the <a href='#prohibited'>Prohibited Activities</a> section — we grant you a non-exclusive, non-transferable, revocable license to access the Services and to download or print a copy of any portion of the Content you have properly gained access to, solely for your personal, non-commercial use or internal business purpose.</p>
            <p style={{ margin: "0 0 22px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Except as set out here, no part of the Services, Content, or Marks may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose without our express prior written permission. Requests go to <a href='mailto:support@remassistance.com'>support@remassistance.com</a>. If we grant permission, you must identify us as owners or licensors and keep all copyright and proprietary notices visible. We reserve all rights not expressly granted. Any breach of these rights is a material breach of these terms, and your right to use the Services terminates immediately.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Your submissions</h3>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>By directly sending us any question, comment, suggestion, idea, feedback, or other information about the Services ("Submissions"), you assign to us all intellectual property rights in that Submission. We own it and may use and disseminate it for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You are responsible for what you post or upload: you confirm you will not send anything illegal, harassing, hateful, harmful, defamatory, obscene, abusive, discriminatory, threatening, sexually explicit, false, or misleading; you waive any moral rights to the extent permitted by law; you warrant your Submissions are original to you or that you have the necessary rights and licenses; and you warrant they contain no confidential information. You agree to reimburse us for any losses we suffer from your breach of this section, a third party's intellectual property rights, or applicable law.</p>
          </div>
  
          <div id='representations'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>3. User representations</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: your information is accurate, you are an adult, and you will use the Services lawfully.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>By using the Services you represent and warrant that: (1) all registration information you submit is true, accurate, current, and complete; (2) you will maintain and promptly update that information; (3) you have the legal capacity and agree to comply with these terms; (4) you are not a minor in your jurisdiction; (5) you will not access the Services through automated or non-human means such as a bot or script; (6) you will not use the Services for any illegal or unauthorized purpose; and (7) your use will not violate any applicable law or regulation.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>If you provide information that is untrue, inaccurate, not current, or incomplete, we may suspend or terminate your account and refuse any current or future use of the Services.</p>
          </div>
  
          <div id='registration'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>4. User registration</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: keep your password confidential — you are responsible for your account.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You may be required to register to use the Services. You agree to keep your password confidential and are responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username if we determine, in our sole discretion, that it is inappropriate, obscene, or otherwise objectionable.</p>
          </div>
  
          <div id='payment'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>5. Purchases and payment</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: keep payment details current; recurring charges continue until you cancel; all payments are in US dollars.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We accept the following forms of payment:</p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "20px" }}>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>Visa</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>Mastercard</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>American Express</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>Discover</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>PayPal</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>Bitcoin</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>REQUEST TOKEN</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>USDC</span>
              <span style={{ fontSize: "13.5px", color: "var(--ink-700)", background: "#fff", border: "1px solid var(--border-default)", borderRadius: "9999px", padding: "8px 15px" }}>TOPI</span>
            </div>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You agree to provide current, complete, and accurate purchase and account information for all purchases, and to promptly update account and payment information — email address, payment method, card expiration date — so we can complete your transactions and contact you as needed. Sales tax is added as we deem required. We may change prices at any time. All payments are in US dollars.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You agree to pay all charges at the prices then in effect, plus any applicable shipping fees, and you authorize us to charge your chosen payment provider upon placing your order. If your order carries recurring charges, you consent to recurring billing without prior approval for each charge, until you cancel. We may correct pricing errors even after payment has been requested or received.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We reserve the right to refuse any order and may limit or cancel quantities purchased per person, household, or order — including orders that appear to be placed by dealers, resellers, or distributors.</p>
          </div>
  
          <div id='refunds'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>6. Refund policy</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: all sales are final.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>All sales are final and no refund will be issued.</p>
          </div>
  
          <div id='prohibited'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>7. Prohibited activities</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: use the Services only for their intended purpose — no scraping, fraud, interference, or unauthorized commercial use.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You may not access or use the Services for any purpose other than the one we make them available for, and never in connection with commercial endeavors we have not specifically endorsed or approved. As a user of the Services, you agree not to:</p>
            <ul style={{ margin: 0, paddingLeft: "22px", display: "flex", flexDirection: "column", gap: "7px", maxWidth: "70ch" }}>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Systematically retrieve data or other content to create a collection, compilation, database, or directory without our written permission</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Trick, defraud, or mislead us or other users, especially to learn sensitive account information such as passwords</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Circumvent, disable, or interfere with security-related features of the Services</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Disparage, tarnish, or otherwise harm us and/or the Services</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Use information obtained from the Services to harass, abuse, or harm another person</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Make improper use of our support services or submit false reports of abuse or misconduct</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Use the Services in a manner inconsistent with any applicable laws or regulations</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Engage in unauthorized framing of or linking to the Services</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Upload or transmit viruses, Trojan horses, or other material — including excessive capital letters and spamming — that interferes with anyone's use of the Services</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Engage in any automated use of the system, such as scripts, data mining, robots, or similar data-gathering and extraction tools</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Delete the copyright or other proprietary rights notice from any Content</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Attempt to impersonate another user or person, or use another user's username</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Upload or transmit any material that acts as a passive or active information collection or transmission mechanism ("spyware," web bugs, 1×1 pixels, and similar)</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Interfere with, disrupt, or create an undue burden on the Services or connected networks</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Harass, annoy, intimidate, or threaten any of our employees or agents</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Attempt to bypass any measures designed to prevent or restrict access to the Services</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Copy or adapt the Services' software, or — except as permitted by applicable law — decipher, decompile, disassemble, or reverse engineer it</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Use, launch, or distribute any unauthorized automated system — spiders, robots, cheat utilities, scrapers, offline readers — beyond standard search engine or browser usage</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Use a buying agent or purchasing agent to make purchases on the Services</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Collect usernames or email addresses of users to send unsolicited email, or create user accounts by automated means or under false pretenses</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Use the Services or Content to compete with us, or for any revenue-generating endeavor or commercial enterprise</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Sell or otherwise transfer your profile</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>Use the Services to advertise or offer to sell goods and services</li>
            </ul>
          </div>
  
          <div id='ugc'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>8. User generated contributions</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: if you do post content, you warrant it is yours, lawful, and not objectionable.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>The Services do not offer users the ability to submit or post content, but we may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Services — text, writings, video, audio, photographs, graphics, comments, suggestions, personal information, or other material (collectively, "Contributions"). Contributions may be viewable by other users and through third-party websites, and are treated in accordance with our Privacy Policy. When you make any Contribution available, you represent and warrant that:</p>
            <ul style={{ margin: "0 0 14px", paddingLeft: "22px", display: "flex", flexDirection: "column", gap: "7px", maxWidth: "70ch" }}>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It does not and will not infringe the proprietary rights — copyright, patent, trademark, trade secret, or moral rights — of any third party</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>You are the creator and owner, or have the necessary licenses, rights, consents, releases, and permissions to authorize us and other users to use it as contemplated by the Services and these terms</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>You have written consent from every identifiable person in it to use their name or likeness</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It is not false, inaccurate, or misleading, and is not unsolicited advertising, promotional material, pyramid schemes, chain letters, spam, or mass mailings</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It is not obscene, lewd, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us), and does not ridicule, mock, disparage, intimidate, or abuse anyone</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It is not used to harass or threaten any person or to promote violence against a specific person or class of people</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It does not violate any applicable law, regulation, or rule, or the privacy or publicity rights of any third party</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It does not violate any law concerning child pornography or intended to protect the health or well-being of minors</li>
              <li style={{ fontSize: "16px", lineHeight: 1.65, color: "var(--ink-700)" }}>It does not include offensive comments connected to race, national origin, gender, sexual preference, or physical handicap</li>
            </ul>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Any use of the Services in violation of the foregoing violates these terms and may result in, among other things, termination or suspension of your rights to use the Services.</p>
          </div>
  
          <div id='license'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>9. Contribution license</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: you keep ownership of your Contributions; we may use your data per the Privacy Policy, and feedback freely.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You and the Services agree that we may access, store, process, and use any information and personal data you provide, following the terms of the Privacy Policy and your choices (including settings). By submitting suggestions or other feedback about the Services, you agree that we can use and share that feedback for any purpose without compensation to you.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We do not assert any ownership over your Contributions — you retain full ownership and all intellectual property rights associated with them. We are not liable for any statements or representations in your Contributions. You are solely responsible for your Contributions, and you agree to exonerate us from any responsibility and to refrain from legal action against us regarding them.</p>
          </div>
  
          <div id='reviews'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>10. Guidelines for reviews</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: reviews must be firsthand, honest, and lawful; posting one grants us a broad license to it.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Where we provide areas to leave reviews or ratings, you must: (1) have firsthand experience with the person or entity being reviewed; (2) avoid offensive profanity or abusive, racist, or hateful language; (3) avoid discriminatory references based on religion, race, gender, national origin, age, marital status, sexual orientation, or disability; (4) avoid references to illegal activity; (5) not be affiliated with competitors if posting negative reviews; (6) not draw conclusions about the legality of conduct; (7) not post false or misleading statements; and (8) not organize campaigns encouraging others to post reviews, positive or negative.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We may accept, reject, or remove reviews at our sole discretion, and have no obligation to screen or delete them. Reviews are not endorsed by us and do not necessarily represent our opinions or those of our affiliates or partners, and we assume no liability for them. By posting a review you grant us a perpetual, non-exclusive, worldwide, royalty-free, fully paid, assignable, and sublicensable license to reproduce, modify, translate, transmit, display, perform, and distribute all content relating to it.</p>
          </div>
  
          <div id='app'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>11. Mobile application license</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: a limited personal license to install and use the App, plus app-store terms from Apple and Google.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Use license</h3>
            <p style={{ margin: "0 0 22px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>If you access the Services via the App, we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the App on wireless devices you own or control, strictly per these terms. You shall not: (1) decompile, reverse engineer, disassemble, or decrypt the App except as permitted by law; (2) make any modification, adaptation, or derivative work from it; (3) violate applicable laws in connection with it; (4) remove or obscure any proprietary notice; (5) use it for any revenue-generating endeavor or purpose it is not designed for; (6) make it available over a network permitting simultaneous use by multiple devices or users; (7) use it to create a competing product, service, or software; (8) use it to send automated queries or unsolicited commercial email; or (9) use our proprietary information or interfaces in the design or development of any applications, accessories, or devices for use with the App.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Apple and Android devices</h3>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>When you obtain the App from the Apple Store or Google Play (each an "App Distributor"): (1) your license is limited to a non-transferable license to use the App on a device running iOS or Android, per the App Distributor's terms of service; (2) we — not the App Distributor — are responsible for maintenance and support as specified in these terms or required by law; (3) if the App fails to conform to an applicable warranty, you may notify the App Distributor, which may refund the purchase price, and has no other warranty obligation; (4) you represent you are not located in a US-embargoed or "terrorist supporting" country and are not on any US government list of prohibited or restricted parties; (5) you must comply with applicable third-party terms of agreement when using the App; and (6) the App Distributors are third-party beneficiaries of this license and may enforce it against you.</p>
          </div>
  
          <div id='thirdparty'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>12. Third-party websites and content</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: links to other sites are provided as-is — once you leave, these terms no longer govern, and you go at your own risk.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>The Services may contain links to other websites ("Third-Party Websites") and articles, photographs, text, graphics, music, sound, video, applications, software, and other content belonging to third parties ("Third-Party Content"). We do not investigate, monitor, or check them for accuracy, appropriateness, or completeness, and are not responsible for them — including their content, opinions, reliability, or privacy practices. Inclusion or linking does not imply our approval or endorsement. If you leave the Services to access them, you do so at your own risk, and you should review the applicable terms and policies of any site you navigate to. Purchases through Third-Party Websites are exclusively between you and the applicable third party — we take no responsibility for them, and you hold us blameless from any harm or losses caused by Third-Party Content or contact with Third-Party Websites.</p>
          </div>
  
          <div id='management'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>13. Services management</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: we may monitor, restrict, and manage the Services to protect our rights and keep them working.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We reserve the right, but not the obligation, to: (1) monitor the Services for violations of these terms; (2) take appropriate legal action against anyone who violates the law or these terms, including reporting to law enforcement; (3) refuse, restrict access to, limit the availability of, or disable any of your Contributions, in our sole discretion; (4) remove or disable files and content that are excessive in size or burdensome to our systems, without notice or liability; and (5) otherwise manage the Services in a manner designed to protect our rights and property and facilitate their proper functioning.</p>
          </div>
  
          <div id='privacy'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>14. Privacy policy</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: by using the Services you agree to our Privacy Policy, and your data is processed in the United States.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We care about data privacy and security. Please review our <a href='/privacy-policy'>Privacy Policy</a> — by using the Services, you agree to be bound by it, and it is incorporated into these terms. The Services are hosted in the United States. If you access them from a region with laws governing personal data collection, use, or disclosure that differ from US law, your continued use transfers your data to the United States, and you expressly consent to have it transferred to and processed there.</p>
          </div>
  
          <div id='termination'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>15. Term and termination</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: we can deny access or terminate accounts at any time, for any reason, without notice.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>These terms remain in full force and effect while you use the Services. Without limiting any other provision, we reserve the right to — in our sole discretion and without notice or liability — deny access to and use of the Services (including blocking certain IP addresses) to any person for any reason or no reason, including breach of any representation, warranty, or covenant in these terms or of any applicable law or regulation. We may terminate your use or participation, or delete your account and any content or information you posted, at any time, without warning.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>If we terminate or suspend your account for any reason, you are prohibited from registering a new account under your name, a fake or borrowed name, or the name of any third party — even if you act on that third party's behalf. We also reserve the right to take appropriate legal action, including civil, criminal, and injunctive redress.</p>
          </div>
  
          <div id='modifications'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>16. Modifications and interruptions</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: the Services may change or go down at any time, and we are not liable when they do.</p>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We reserve the right to change, modify, or remove the contents of the Services at any time, for any reason, at our sole discretion, without notice — and to modify or discontinue all or part of the Services. We have no obligation to update any information, and we will not be liable to you or any third party for any modification, price change, suspension, or discontinuance.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We cannot guarantee the Services will be available at all times — hardware, software, or other problems, or maintenance, may cause interruptions, delays, or errors. You agree that we have no liability for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance, and nothing in these terms obligates us to maintain and support the Services or supply corrections, updates, or releases.</p>
          </div>
  
          <div id='law'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>17. Governing law</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: Texas law governs.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>These terms and your use of the Services are governed by and construed in accordance with the laws of the State of Texas, applicable to agreements made and to be entirely performed within the State of Texas, without regard to its conflict of law principles.</p>
          </div>
  
          <div id='disputes'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>18. Dispute resolution</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: 20 days of informal negotiation first, then binding individual arbitration in Harris County, Texas.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Informal negotiations</h3>
            <p style={{ margin: "0 0 22px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>To expedite resolution and control costs, you and we (the "Parties") agree to first attempt to negotiate any dispute related to these terms (except those expressly excluded below) informally for at least twenty (20) days before initiating arbitration. Informal negotiations commence upon written notice from one Party to the other.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Binding arbitration</h3>
            <p style={{ margin: "0 0 14px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>If informal negotiation fails, the dispute will be finally and exclusively resolved by binding arbitration. <strong style={{ color: "var(--brand-navy)" }}>You understand that without this provision, you would have the right to sue in court and have a jury trial.</strong> Arbitration is commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA Consumer Rules. Your fees and share of arbitrator compensation are governed and, where appropriate, limited by the AAA Consumer Rules; if the arbitrator finds costs excessive, we pay all arbitration fees and expenses. Arbitration may be conducted in person, by document submission, by phone, or online; the arbitrator's decision is in writing, follows applicable law, and may be challenged if it does not. Except where the AAA rules or applicable law require otherwise, arbitration takes place in Harris County, Texas. The Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or confirm, modify, vacate, or enter judgment on the award.</p>
            <p style={{ margin: "0 0 22px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>If a dispute proceeds in court rather than arbitration, it shall be commenced in the state and federal courts located in Harris County, Texas, and the Parties consent to — and waive all defenses of lack of personal jurisdiction and forum non conveniens with respect to — venue and jurisdiction there. The UN Convention on Contracts for the International Sale of Goods and UCITA are excluded. No dispute may be commenced more than one (1) year after the cause of action arose. If this provision is found illegal or unenforceable, the dispute shall be decided by a court of competent jurisdiction within the courts listed above, and the Parties submit to that court's personal jurisdiction.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Restrictions</h3>
            <p style={{ margin: "0 0 22px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Any arbitration shall be limited to the dispute between the Parties individually. To the full extent permitted by law: (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any dispute to be arbitrated on a class-action basis or to use class action procedures; and (c) there is no right or authority for any dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.</p>
            <h3 style={{ margin: "0 0 10px", fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 700, color: "var(--brand-navy)" }}>Exceptions</h3>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>The following disputes are not subject to informal negotiations or binding arbitration: (a) disputes seeking to enforce, protect, or concerning the validity of a Party's intellectual property rights; (b) disputes arising from allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief. If this provision is found illegal or unenforceable, such a dispute shall be decided by a court of competent jurisdiction within the courts listed above.</p>
          </div>
  
          <div id='corrections'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>19. Corrections</h2>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>There may be information on the Services containing typographical errors, inaccuracies, or omissions — including descriptions, pricing, and availability. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update information at any time, without prior notice.</p>
          </div>
  
          <div id='disclaimer'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>20. Disclaimer</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: the Services are provided as-is and as-available, and you use them at your sole risk.</p>
            <div style={{ background: "#fff", border: "1px solid var(--border-default)", borderRadius: "10px", padding: "24px 26px" }}>
              <p style={{ margin: 0, fontSize: "14.5px", lineHeight: 1.7, color: "var(--ink-700)", textTransform: "uppercase", letterSpacing: "0.01em" }}>The Services are provided on an as-is and as-available basis. You agree that your use of the Services will be at your sole risk. To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the Services and your use thereof, including the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We make no warranties or representations about the accuracy or completeness of the Services' content or the content of any linked websites or mobile applications, and we assume no liability or responsibility for any (1) errors, mistakes, or inaccuracies of content and materials, (2) personal injury or property damage resulting from your access to and use of the Services, (3) unauthorized access to or use of our secure servers and/or any personal or financial information stored therein, (4) interruption or cessation of transmission to or from the Services, (5) bugs, viruses, Trojan horses, or the like transmitted to or through the Services by any third party, and/or (6) errors or omissions in any content and materials, or loss or damage of any kind incurred from the use of content posted, transmitted, or otherwise made available via the Services. We do not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the Services or any hyperlinked website, and we will not be a party to or responsible for monitoring any transaction between you and third-party providers. Use your best judgment and exercise caution where appropriate.</p>
            </div>
          </div>
  
          <div id='liability'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>21. Limitations of liability</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: our liability is capped at what you paid us in the six months before the claim.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>In no event will we or our directors, employees, or agents be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages — including lost profit, lost revenue, or loss of data — arising from your use of the Services, even if we have been advised of the possibility of such damages. Notwithstanding anything to the contrary herein, our liability to you for any cause whatsoever, regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to us during the six (6) month period prior to any cause of action arising. Certain US state laws and international laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages; if these laws apply to you, some or all of the above disclaimers or limitations may not apply, and you may have additional rights.</p>
          </div>
  
          <div id='indemnification'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>22. Indemnification</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: if your use of the Services causes us to be sued, you cover the loss.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>You agree to defend, indemnify, and hold us harmless — including our subsidiaries, affiliates, and all respective officers, agents, partners, and employees — from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of: (1) use of the Services; (2) breach of these terms; (3) any breach of your representations and warranties; (4) your violation of the rights of a third party, including intellectual property rights; or (5) any overt harmful act toward any other user of the Services with whom you connected via the Services. We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense. We will use reasonable efforts to notify you of any such claim upon becoming aware of it.</p>
          </div>
  
          <div id='userdata'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>23. User data</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: we back up regularly, but you are responsible for your own data.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>We will maintain certain data that you transmit to the Services for the purpose of managing their performance, as well as data relating to your use of the Services. Although we perform regular routine backups, you are solely responsible for all data you transmit or that relates to activity you have undertaken using the Services. You agree that we shall have no liability to you for any loss or corruption of such data, and you hereby waive any right of action against us arising from any such loss or corruption.</p>
          </div>
  
          <div id='electronic'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>24. Electronic communications, transactions, and signatures</h2>
            <p style={{ margin: "0 0 20px", fontSize: "14.5px", lineHeight: 1.6, color: "var(--brand-blue)", fontWeight: 600 }}>In short: email and electronic signatures count as written communication and signatures.</p>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>Visiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications and agree that all agreements, notices, disclosures, and other communications we provide electronically — via email and on the Services — satisfy any legal requirement that such communication be in writing. You agree to the use of electronic signatures, contracts, orders, and other records, and to electronic delivery of notices, policies, and records of transactions initiated or completed by us or via the Services. You waive any rights or requirements under any laws that require an original signature, delivery or retention of non-electronic records, or payments or credits by non-electronic means.</p>
          </div>
  
          <div id='california'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>25. California users and residents</h2>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834, or by telephone at <a href='tel:+18009525210'>(800) 952-5210</a> or <a href='tel:+19164451254'>(916) 445-1254</a>.</p>
          </div>
  
          <div id='misc'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>26. Miscellaneous</h2>
            <p style={{ margin: 0, fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>These terms and any policies or operating rules we post on or about the Services constitute the entire agreement between you and us. Our failure to exercise or enforce any right or provision is not a waiver of it. These terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time, and we are not responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision is found unlawful, void, or unenforceable, it is severable and does not affect the validity and enforceability of the remaining provisions. No joint venture, partnership, employment, or agency relationship is created between you and us by these terms or your use of the Services. You agree these terms will not be construed against us by virtue of having drafted them, and you waive any defenses based on their electronic form or the lack of signing by the parties.</p>
          </div>
  
          <div id='contact'>
            <h2 style={{ margin: "0 0 8px", fontFamily: "var(--font-display)", fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.015em", color: "var(--brand-navy)" }}>27. How to contact us</h2>
            <p style={{ margin: "0 0 20px", fontSize: "16px", lineHeight: 1.7, color: "var(--ink-700)", maxWidth: "68ch" }}>To resolve a complaint regarding the Services or receive further information about using them:</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: "14px" }}>
              <div style={{ background: "#fff", border: "1px solid var(--border-default)", borderRadius: "10px", padding: "22px 24px", minWidth: 0, overflowWrap: "anywhere" }}>
                <div style={{ fontFamily: "var(--font-mono)", fontSize: "11.5px", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--brand-blue)", marginBottom: "8px" }}>Phone and email</div>
                <a href='tel:+18322302194' style={{ fontSize: "15.5px", fontWeight: 600, textDecoration: "none" }}>(832) 230-2194</a>
                <div style={{ marginTop: "8px" }}><a href='mailto:support@remassistance.com' style={{ fontSize: "15.5px", fontWeight: 600, textDecoration: "none" }}>support@remassistance.com</a></div>
                <div style={{ marginTop: "8px", fontSize: "14.5px", color: "var(--ink-600)" }}>Fax: (832) 505-4548</div>
              </div>
              <div style={{ background: "#fff", border: "1px solid var(--border-default)", borderRadius: "10px", padding: "22px 24px", minWidth: 0, overflowWrap: "anywhere" }}>
                <div style={{ fontFamily: "var(--font-mono)", fontSize: "11.5px", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--brand-blue)", marginBottom: "8px" }}>By post</div>
                <p style={{ margin: 0, fontSize: "15px", lineHeight: 1.6, color: "var(--ink-700)" }}>Rem Assistance Inc.<br />3733 Westheimer Rd, Ste #1-2058<br />Houston, TX 77027<br />United States</p>
              </div>
            </div>
          </div>
  
        </div>
      </div>
    </section>
  
  
  
    </main>
  );
}
